args = commandArgs()
basename = sub(".R$", "", sub("^--file=(.*/)?", "", args[grep("^--file=", args)]))
if (length(basename) != 0)
    quartz(type="pdf", file=paste0(basename, ".pdf"), width=5, height=3)
t = replicate(1000000, {x=runif(12); (mean(x)-0.5)/(sd(x)/sqrt(12)) })
par(family="Palatino")
par(mgp=c(1.5,0.5,0)) # title and axis margins. default: c(3,1,0)
par(mar=c(2,2,1,1)+0.1) # bottom, left, top, right margins. default: c(5,4,4,2)+0.1
s = seq(-15,15,0.2)
hist(t, freq=FALSE, col="gray", xlim=c(-4,4), main="", xlab="", ylab="", breaks=s)
curve(dt(x, 11), add=TRUE)
curve(dnorm(x), lty=2, add=TRUE)
dev.off()
