args = commandArgs()
basename = sub(".R$", "", sub("^--file=(.*/)?", "", args[grep("^--file=", args)]))
if (length(basename) != 0)
    quartz(type="pdf", file=paste0(basename, ".pdf"), width=7, height=5)
par(family="HiraKakuProN-W3")
par(mgp=c(2,0.8,0)) # title and axis margins. default: c(3,1,0)
par(mar=c(3,4,2,2)+0.1) # bottom, left, top, right margins. default: c(5,4,4,2)+0.1
x = read.csv("../data/nikkyoso.csv", fileEncoding="CP932")
x$日教組票 = round(x$H16参院選那谷屋正義 + x$H19参院選神本みえ子)
plot(x$総合点, x$日教組票, pch=16, log="y", xlab="総合点", ylab="", bty="l", las=1)
mtext("日教組票", at=c(410,52000))
abline(v=c(476.3, 498.85))
abline(h=c(1994, 8127.5))
dev.off()
