args = commandArgs()
basename = sub(".R$", "", sub("^--file=(.*/)?", "", args[grep("^--file=", args)]))
if (length(basename) != 0)
    quartz(type="pdf", file=paste0(basename, ".pdf"), width=8, height=3)
par(family="Palatino")
par(mgp=c(2,0.8,0)) # title and axis margins. default: c(3,1,0)
par(mar=c(3,3,2,2)+0.1) # bottom, left, top, right margins. default: c(5,4,4,2)+0.1
par(mfrow = c(1,2))
barplot(dpois(0:20, 5), names.arg=0:20, ylim=c(0,0.2), xlab="", ylab="", las=1)
barplot(dexp(0:20, 1/5), names.arg=0:20, ylim=c(0,0.2), xlab="", ylab="", las=1)
dev.off()
